import Head from 'next/head';
import { useHistory } from 'react-router-dom';
import { useIsAuthenticated } from 'react-auth-kit';

export default function Home() {
  const isAuthenticated = useIsAuthenticated();
  const history = useHistory();

  if (isAuthenticated()) {
    history.replace('/home');
  } else {
    history.replace('/login');
  }

  return (

    <div>
      <Head>
        <title>Home Page!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Home Page! </h1>
    </div>
  );
}
