import Head from 'next/head';

export default function Login() {
  return (

    <div>
      <Head>
        <title>Login Page!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Login Page! </h1>
    </div>
  );
}
