import Head from 'next/head';

export default function Register() {
  return (
    <div>
      <Head>
        <title>Register Page!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> Register Page! </h1>
    </div>
  );
}
